/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Kernel.LoginPC;
import java.util.Vector;

/**
 *
 * @author NickyVo
 */
public class Account extends javax.swing.JFrame {
Vector log_vt = LoginPC.getEmployeeInformation();
private String accID;

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("CIS-Account Details");
        this.setSize(655, 610);
        this.setResizable(false);
        getData();
          
    }
 
public void getData( )
    {
            
            for(int i=0; i< log_vt.size(); i++)
            {
                Vector temp=(Vector) log_vt.elementAt(i);
              accID=Login.EmpID;
              if(accID.equals(temp.elementAt(0).toString()))
                {
                   
                    lb_Id.setText(temp.elementAt(0).toString());
                    if(temp.elementAt(1).toString().trim().equals("1")){
                        lb_Type.setText("Administrator");
                    }else{
                        lb_Type.setText("Employee");
                    }                    
                    lb_Name.setText(temp.elementAt(2).toString());
                    lb_Age.setText(temp.elementAt(3).toString());
                    lb_Mail.setText(temp.elementAt(4).toString());
                    lb_Phone.setText(temp.elementAt(5).toString());
                    
                    
                 //   lb_Pass.setText(temp.elementAt(6).toString());
                    break;
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_Id = new javax.swing.JLabel();
        lb_Type = new javax.swing.JLabel();
        lb_Age = new javax.swing.JLabel();
        lb_Mail = new javax.swing.JLabel();
        lb_Phone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        changInfo = new javax.swing.JLabel();
        changePassword = new javax.swing.JLabel();
        lb_Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 150, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Emp Id:");

        jLabel4.setText("Emp Type:");

        jLabel5.setText("Emp Age:");

        jLabel6.setText("Emp Mail:");

        jLabel7.setText("Emp Phone:");

        lb_Id.setText("jLabel9");

        lb_Type.setText("jLabel10");

        lb_Age.setText("jLabel11");

        lb_Mail.setText("jLabel12");

        lb_Phone.setText("jLabel13");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnExit.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        changInfo.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        changInfo.setForeground(new java.awt.Color(51, 153, 235));
        changInfo.setText("Change Info");
        changInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changInfoMouseClicked(evt);
            }
        });

        changePassword.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        changePassword.setForeground(new java.awt.Color(51, 153, 235));
        changePassword.setText("Change Password");
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
        });

        lb_Name.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        lb_Name.setText("jLabel16");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Phone)
                    .addComponent(lb_Age)
                    .addComponent(lb_Mail)
                    .addComponent(lb_Type)
                    .addComponent(lb_Id)
                    .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lb_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_Id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_Type))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_Age))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_Mail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Phone)
                    .addComponent(jLabel7))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePassword)
                    .addComponent(changInfo))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 610, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgTemplete.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        this.setVisible(false);
        new PasswordChange().setVisible(true);
    }//GEN-LAST:event_changePasswordMouseClicked

    private void changInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changInfoMouseClicked
        this.setVisible(false);
        new ChangeInfo().setVisible(true);
    }//GEN-LAST:event_changInfoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changInfo;
    private javax.swing.JLabel changePassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Age;
    private javax.swing.JLabel lb_Id;
    private javax.swing.JLabel lb_Mail;
    private javax.swing.JLabel lb_Name;
    private javax.swing.JLabel lb_Phone;
    private javax.swing.JLabel lb_Type;
    // End of variables declaration//GEN-END:variables
}
