/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Campaign;
import Kernel.CampaignPC;
import Kernel.Validation;
import Kernel.dataPC;
import java.awt.Color;
import java.sql.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asus
 */
public class CampaignMaster extends javax.swing.JFrame {
    int row =0;
    int dateStt=0;
    int per=0;
    boolean clickable =true;
    boolean update = false;
    /**
     * Creates new form CampaignMaster
     */
    public CampaignMaster() {
        initComponents();
        this.setTitle("CIS-Campaign Master");
        this.setSize(800, 636);
        this.setResizable(false);
        if(!Login.admin){
            lb_Admin.setEnabled(false);
            lb_Camp.setEnabled(false);
            lb_Pro.setEnabled(false);
        }
        dataPC.readToComboBox("[CIS].[dbo].[Advertisement]",cmb_Ad,"AdType");
        dataPC.readToComboBox("[CIS].[dbo].[Product]",cmb_Pro,"ProName");
        loadDataToTable();
        reset();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpCamp = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rd_Name = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        rd_ID = new javax.swing.JRadioButton();
        btn_Find = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Camp = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_CampId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Des = new javax.swing.JTextArea();
        btn_create = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_CampName = new javax.swing.JTextField();
        txt_Start = new javax.swing.JTextField();
        txt_End = new javax.swing.JTextField();
        txt_per = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_AdID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmb_Ad = new javax.swing.JComboBox();
        chk_finish = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ProID = new javax.swing.JTextField();
        cmb_Pro = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_Home = new javax.swing.JLabel();
        lb_Admin = new javax.swing.JLabel();
        lb_Pro = new javax.swing.JLabel();
        lb_Camp = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_Est = new javax.swing.JLabel();
        lb_Act = new javax.swing.JLabel();
        lb_Stt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_Acc = new javax.swing.JLabel();
        lb_SignOut = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Menu_Home = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Menu_Exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Campaign Master");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        btnGrpCamp.add(rd_Name);
        rd_Name.setText("Campaign Name");
        getContentPane().add(rd_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 139, -1));

        btnGrpCamp.add(rd_ID);
        rd_ID.setSelected(true);
        rd_ID.setText("Campaign ID");
        getContentPane().add(rd_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        btn_Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSearch.png"))); // NOI18N
        btn_Find.setText("Find");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campaign List"));

        tb_Camp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campaign ID", "Campaign Name", "Product", "StartDate", "EndDate", "Period", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Camp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_CampMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Camp);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Product Name:");

        jLabel12.setText("Campaign ID:");

        jLabel13.setText("Description :");

        txt_Des.setColumns(20);
        txt_Des.setRows(5);
        jScrollPane2.setViewportView(txt_Des);

        btn_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnInsert.png"))); // NOI18N
        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnUpdate.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDelete.png"))); // NOI18N
        btn_del.setText("Delete");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRefresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel14.setText("Campaign Name:");

        jLabel15.setText("Start Date:");

        jLabel16.setText("Finish Date:");

        jLabel17.setText("Period:");

        txt_CampName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CampNameActionPerformed(evt);
            }
        });

        txt_Start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_StartFocusLost(evt);
            }
        });
        txt_Start.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_StartInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txt_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EndActionPerformed(evt);
            }
        });
        txt_End.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_EndFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_EndFocusLost(evt);
            }
        });
        txt_End.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_EndInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txt_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_perActionPerformed(evt);
            }
        });

        jLabel18.setText("(dd/mm/yyyy)");

        jLabel19.setText("(dd/mm/yyyy)");

        jLabel1.setText("Ad ID:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBrowser.png"))); // NOI18N
        jButton1.setText("Ad Master");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ad Type:");

        cmb_Ad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select>" }));
        cmb_Ad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_AdItemStateChanged(evt);
            }
        });

        jLabel3.setText("Is Finished:");

        jLabel4.setText("Product ID:");

        cmb_Pro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select>" }));
        cmb_Pro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProItemStateChanged(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(*)");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("(*)");

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("(*)");

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("(*)");

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("(*)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmb_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(txt_CampId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txt_ProID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chk_finish))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_create)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_del)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_AdID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                            .addComponent(txt_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel18))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                            .addComponent(txt_End, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel19))
                                                        .addComponent(cmb_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(13, 13, 13)))
                                            .addComponent(txt_CampName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_per, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(25, 25, 25)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_CampId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmb_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_ProID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addComponent(chk_finish, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CampName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txt_AdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_create)
                    .addComponent(btn_update)
                    .addComponent(btn_del)
                    .addComponent(btn_refresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 650, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Home.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Home.setForeground(new java.awt.Color(51, 153, 255));
        lb_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconHome.png"))); // NOI18N
        lb_Home.setText("Home");
        lb_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HomeMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        lb_Admin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Admin.setForeground(new java.awt.Color(51, 153, 255));
        lb_Admin.setText("Administration");
        lb_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AdminMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 114, -1));

        lb_Pro.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Pro.setForeground(new java.awt.Color(51, 153, 255));
        lb_Pro.setText("Product Master");
        lb_Pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ProMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 114, -1));

        lb_Camp.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Camp.setForeground(new java.awt.Color(51, 153, 255));
        lb_Camp.setText("Campaign Master");
        lb_Camp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_CampMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Camp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 146, 10));

        lb_Est.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Est.setForeground(new java.awt.Color(51, 153, 255));
        lb_Est.setText("Estimate Budget");
        lb_Est.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_EstMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, -1));

        lb_Act.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Act.setForeground(new java.awt.Color(51, 153, 255));
        lb_Act.setText("Actual Budget");
        lb_Act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ActMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 106, -1));

        lb_Stt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Stt.setForeground(new java.awt.Color(51, 153, 255));
        lb_Stt.setText("Statistics");
        lb_Stt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SttMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 146, 10));

        lb_Acc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Acc.setForeground(new java.awt.Color(51, 153, 255));
        lb_Acc.setText("My Account");
        lb_Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AccMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));

        lb_SignOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_SignOut.setForeground(new java.awt.Color(51, 153, 255));
        lb_SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLogout.png"))); // NOI18N
        lb_SignOut.setText("Sign Out");
        lb_SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SignOutMouseClicked(evt);
            }
        });
        jPanel1.add(lb_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgMenu.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 580));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgTemplete.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 580));

        jMenu3.setText("Menu");

        Menu_Home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        Menu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_HomeActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Home);
        jMenu3.add(jSeparator3);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Exit.setText("Exit");
        Menu_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ExitMouseClicked(evt);
            }
        });
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Exit);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem1.setText("User Guide is temporarily not available");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Campaign getCampaign()
    {
        Campaign cam=new Campaign();
        Date start = Validation.convertStringToDate(txt_Start.getText().trim());
        Date end = Validation.convertStringToDate(txt_End.getText().trim());
        
        if(update == true){
            cam.setCampaignID(Integer.parseInt(txt_CampId.getText().trim()));
        }
        cam.setCampaignName(txt_CampName.getText().trim());
        cam.setProductID(txt_ProID.getText().toString().trim());
        cam.setProductName(cmb_Pro.getSelectedItem().toString().trim());
        cam.setStartDate(Validation.convertStringToDate(txt_Start.getText().trim()));
        cam.setEndDate(Validation.convertStringToDate(txt_End.getText().trim()));
        cam.setPeriod(start.compareTo(end));
        cam.setAdID(txt_AdID.getText());
        cam.setAdType(cmb_Ad.getSelectedItem().toString().trim());
        cam.setDescription(txt_Des.getText().toString().trim());
        cam.setEnded(chk_finish.isSelected());

        return cam;
    }
    
 private void reset()
    {
        loadDataToTable();
        Validation.setBlankField(new JTextComponent[]{txt_CampId,txt_ProID,txt_Des,txt_CampName,txt_AdID,txt_Start,txt_End,txt_per});
        btn_del.setEnabled(true);
        btn_Find.setEnabled(true);
        btn_create.setEnabled(true);
        btn_create.setText("Create");
        btn_update.setEnabled(true);
        btn_update.setText("Update");
        btn_refresh.setEnabled(true);
        
        txt_AdID.setEnabled(false);
        txt_CampId.setEnabled(false);
        txt_ProID.setEnabled(false);
        txt_per.setEnabled(false);
        txt_Des.setEnabled(false);
        txt_CampName.setEnabled(false);
        txt_Start.setEnabled(false);
        txt_End.setEnabled(false);
        chk_finish.setEnabled(false);
        cmb_Ad.setEnabled(false);
        cmb_Pro.setEnabled(false);
        cmb_Ad.setSelectedIndex(0);
        cmb_Pro.setSelectedIndex(0);
        row =0;
        clickable = true;
        dateStt=0;
        per=0;
        clickable =true;
        update = false;
    }
    private void loadDataToTable()
    {
        Vector tit=new Vector();
        tit.add("CampID");
        tit.add("CampName");
        tit.add("ProID");
        tit.add("StartDate");
        tit.add("EndDate");
        tit.add("Period");
        tit.add("AdID");
        tit.add("AdType");
        tit.add("Description");
        tit.add("Ended");
        Vector data=CampaignPC.readCampaign();
        tb_Camp.setModel(new DefaultTableModel(data, tit));
    }
    private void txt_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EndActionPerformed

    private void tb_CampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CampMouseClicked
         if(clickable == true){
             row = tb_Camp.getSelectedRow();
         boolean fn=false;
         
        if(row!=-1){
            
            txt_CampId.setText(""+tb_Camp.getValueAt(row, 0));
            txt_CampId.setEditable(false);
            
            txt_CampName.setText(""+tb_Camp.getValueAt(row, 1));
            txt_CampName.setEditable(false);
            
            txt_ProID.setText(""+tb_Camp.getValueAt(row, 2));
            txt_ProID.setEditable(false);
           
            String proName = dataPC.getAnotherField("Product", "ProID", "ProName", tb_Camp.getValueAt(row, 2).toString());
            cmb_Pro.setSelectedItem(proName);
            cmb_Pro.setEnabled(false);
            
            txt_Start.setText(""+tb_Camp.getValueAt(row, 3));
            txt_Start.setEditable(false);
            
            txt_End.setText(""+tb_Camp.getValueAt(row, 4));
            txt_End.setEditable(false);
            
            txt_per.setText(""+tb_Camp.getValueAt(row, 5));
            txt_per.setEditable(false);
            
            txt_AdID.setText(""+tb_Camp.getValueAt(row, 6));
            txt_AdID.setEditable(false);
           
            cmb_Ad.setSelectedItem(tb_Camp.getValueAt(row, 7));
            cmb_Ad.setEnabled(false);
            
            txt_Des.setText(""+tb_Camp.getValueAt(row, 8));
            txt_Des.setEditable(false);
           
            if(tb_Camp.getValueAt(row, 9).equals("Yes")) {
                fn=true;
            }
            else{
                fn=false;
            }
            chk_finish.setSelected(fn);
            chk_finish.setEnabled(false);
        }
         }
    }//GEN-LAST:event_tb_CampMouseClicked

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        int cr_row = 0;
        if(evt.getActionCommand().equals("Create")){
            reset();
            clickable = false;
            btn_create.setText("Save");
            //Deactivate buttons
            btn_del.setEnabled(false);
            btn_Find.setEnabled(false);
            btn_refresh.setEnabled(true);
            btn_update.setEnabled(false);
            //Activate Edit for textbox and combobox and checkbox
            txt_CampName.setEnabled(true);
            
            txt_CampName.setEditable(true);
            txt_Start.setEnabled(true);
            txt_Start.setEditable(true);
            txt_End.setEnabled(true);
            txt_End.setEditable(true);
            txt_Des.setEnabled(true);
            txt_Des.setEditable(true);
            
            cmb_Ad.setEnabled(true);
            cmb_Pro.setEnabled(true);
            chk_finish.setEnabled(false);
            chk_finish.setSelected(false);
                      
        }
        if(evt.getActionCommand().equals("Save")){
            if(Validation.isEmpty(txt_CampName.getText().trim())){
                Validation.showMess("Empty value is not allowed");
                txt_CampName.requestFocus();
                txt_CampName.setBackground(new Color(255,153,153));
                return;
            }else if(((txt_CampName.getText().trim()).length()>50))
        {
            Validation.showMess("Campaign Name is restricted to 50 characters");
            txt_CampName.requestFocus();
            txt_CampName.setBackground(new Color(255,153,153));
            return;
        }
            else if(cmb_Pro.getSelectedIndex()==0){
                Validation.showMess("Must choose a product");
                cmb_Pro.requestFocus();
                return;
            }
            else if(cmb_Ad.getSelectedIndex()==0){
                Validation.showMess("Must choose an Ad-Method");
                cmb_Ad.requestFocus();
                return;
            }
         if(!Validation.validateComponents(new JTextComponent[]{txt_ProID,txt_CampName,txt_Start,txt_End,txt_AdID,}))
        {
            return;
        }          
        else if(!Validation.isDate(txt_Start.getText()))
        {
            Validation.showMess("Date invalid fomat dd/mm/yyyy ");
            txt_Start.requestFocus();
            txt_Start.setBackground(new Color(255,153,153));
            return;
        }
        else if(!Validation.isDate(txt_End.getText()))
        {
            Validation.showMess("Date invalid fomat dd/mm/yyyy ");
            txt_End.requestFocus();
            txt_End.setBackground(new Color(255,153,153));
            return;
        }
       
        else if(Validation.convertStringToDate(txt_Start.getText()).after(Validation.convertStringToDate(txt_End.getText())))
        {
            Validation.showMess("Finish date must be after start date  ");
            txt_End.setBackground(new Color(255,153,153));
            txt_End.requestFocus();
            return;            
        }else if(((txt_Des.getText().trim()).length()>150))
        {
            Validation.showMess("Campaign's Description is restricted to 150 characters");
            txt_Des.requestFocus();
            txt_Des.setBackground(new Color(255,153,153));
            return;
        }          
        String mess=CampaignPC.insertCampaign(getCampaign());
        new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
        reset();
        btn_create.setText("Create");
        clickable = true;
        //Deactivate buttons
        reset();
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void cmb_ProItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProItemStateChanged
        if(cmb_Pro.getSelectedIndex()==0){
            txt_ProID.setText(null);
        }else{
            String proID = dataPC.getAnotherField("Product", "ProName", "ProID", cmb_Pro.getSelectedItem().toString().trim());
            txt_ProID.setText(proID);
        }
    }//GEN-LAST:event_cmb_ProItemStateChanged

    private void cmb_AdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_AdItemStateChanged
        if(cmb_Ad.getSelectedIndex()==0){
            txt_AdID.setText(null);
        }else{
            String values=(String)cmb_Ad.getSelectedItem();
            txt_AdID.setText(dataPC.getAnotherField("[CIS].[dbo].[Advertisement]","AdType","AdID", values));
        }
    }//GEN-LAST:event_cmb_AdItemStateChanged

    private void txt_EndInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_EndInputMethodTextChanged
        
    }//GEN-LAST:event_txt_EndInputMethodTextChanged

    private void txt_StartInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_StartInputMethodTextChanged
        
    }//GEN-LAST:event_txt_StartInputMethodTextChanged

    private void txt_EndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EndFocusLost
       
    }//GEN-LAST:event_txt_EndFocusLost

    private void txt_StartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_StartFocusLost
      
    }//GEN-LAST:event_txt_StartFocusLost

    private void txt_EndFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EndFocusGained
      
    }//GEN-LAST:event_txt_EndFocusGained

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        int ByID=1;
        int ByName=2;
        Vector vt;
        if(Validation.isEmpty(txt_search.getText()))
        {
            Validation.showMess("Please enter any words to find");
            txt_search.requestFocus();
            txt_search.setBackground(new Color(255,153,153));
            return;
        }
        if(rd_ID.isSelected())
        {
            vt=CampaignPC.FindCampaign(txt_search.getText(), ByID);
        }
        else
        {
            vt=CampaignPC.FindCampaign(txt_search.getText(), ByName);
        }
        Vector tit=new Vector();
        tit.add("CampID");
        tit.add("CampName");
        tit.add("ProID");
        tit.add("StartDate");
        tit.add("EndDate");
        tit.add("Period");
        tit.add("AdID");
        tit.add("AdType");
        tit.add("Description");
        tit.add("Ended");
        tb_Camp.setModel(new DefaultTableModel(vt, tit));
        txt_search.setText("");
    }//GEN-LAST:event_btn_FindActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(evt.getActionCommand().equals("Update")){
             if (tb_Camp.getSelectedRow() == -1) {
            new ShowMessageDialog(null, true, "Please choose a row",  ShowMessageDialog.MESSAGE);
            return;
            }else{
            clickable = false;
            btn_update.setText("Save");
            //Deactivate buttons
            btn_del.setEnabled(false);
            
            btn_refresh.setEnabled(true);
            btn_create.setEnabled(false);
            //Activate Edit for textbox and combobox and checkbox
            txt_CampName.setEnabled(true);
            txt_CampName.setEditable(true);
            txt_Start.setEnabled(true);
            txt_Start.setEditable(true);
            txt_End.setEnabled(true);
            txt_End.setEditable(true);
            txt_Des.setEnabled(true);
            txt_Des.setEditable(true);
            
            cmb_Ad.setEnabled(true);
            cmb_Pro.setEnabled(true);
            chk_finish.setEnabled(false);
            
            //Set marsk for CAMPID
            txt_CampId.setText(tb_Camp.getValueAt(row, 0).toString().trim());
            
            //set update protocol
            this.update = true;
             }
        }
        if(evt.getActionCommand().equals("Save")){
            if(!Validation.validateComponents(new JTextComponent[]{txt_ProID,txt_CampName,txt_Start,txt_End,txt_AdID,}))
        {
            return;
        }else if(((txt_CampName.getText().trim()).length()>50))
        {
            Validation.showMess("Campaign Name is restricted to 50 characters");
            txt_CampName.requestFocus();
            txt_CampName.setBackground(new Color(255,153,153));
            return;
        }      
        else if(!Validation.isDate(txt_Start.getText()))
        {
            Validation.showMess("Date invalid fomat dd/mm/yyyy ");
            txt_Start.requestFocus();
            txt_Start.setBackground(new Color(255,153,153));
            return;
        }
        else if(!Validation.isDate(txt_End.getText()))
        {
            Validation.showMess("Date invalid fomat dd/mm/yyyy ");
            txt_End.requestFocus();
            txt_End.setBackground(new Color(255,153,153));
            return;
        }
       
        else if(Validation.convertStringToDate(txt_Start.getText()).after(Validation.convertStringToDate(txt_End.getText())))
        {
            Validation.showMess("Finish date must be after start date  ");
            txt_End.setBackground(new Color(255,153,153));
            txt_End.requestFocus();
            return;            
        }else if(((txt_Des.getText().trim()).length()>150))
        {
            Validation.showMess("Campaign's Description is restricted to 150 characters");
            txt_Des.requestFocus();
            txt_Des.setBackground(new Color(255,153,153));
            return;
        }        
        String mess=CampaignPC.updateCampaign(getCampaign());
        new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
        reset();
        btn_update.setText("Update");
        clickable = true;
        update= false;
        //Reactivate buttons
            btn_del.setEnabled(true);
            btn_Find.setEnabled(true);
            btn_refresh.setEnabled(true);
            btn_create.setEnabled(true);
            //Detivate Edit for textbox and combobox and checkbox
            txt_CampName.setEditable(false);
            txt_Start.setEditable(false);
            txt_End.setEditable(false);
            txt_Des.setEditable(false);
            
            cmb_Ad.setEnabled(false);
            cmb_Pro.setEnabled(false);
            chk_finish.setEnabled(false);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
                if(tb_Camp.getSelectedRow()==-1)
        {
            new ShowMessageDialog(null, true,"Please chose a row",ShowMessageDialog.MESSAGE);
            return;
        }
        new ShowMessageDialog(null, true,"Do you want delete campaign",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
           String mess= CampaignPC.deleteCampaign(txt_CampId.getText());
           new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
           reset();
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        reset();
        loadDataToTable();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new AdvertisementManagement().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked

    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HomeActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Menu_HomeActionPerformed

    private void Menu_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ExitMouseClicked

    }//GEN-LAST:event_Menu_ExitMouseClicked

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        new ShowMessageDialog(this, true, "Do you want to exit the program ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void lb_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HomeMouseClicked
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_lb_HomeMouseClicked

    private void lb_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AdminMouseClicked
        if(lb_Admin.isEnabled()){
            this.setVisible(false);
            new Administration().setVisible(true);
        }
    }//GEN-LAST:event_lb_AdminMouseClicked

    private void lb_ProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ProMouseClicked
        if(lb_Pro.isEnabled()){
            this.setVisible(false);
            new ProductMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_ProMouseClicked

    private void lb_CampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_CampMouseClicked
        if(lb_Camp.isEnabled())
        {
            this.setVisible(false);
            new CampaignMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_CampMouseClicked

    private void lb_EstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_EstMouseClicked
        this.setVisible(false);
        new EstimateBudget().setVisible(true);
    }//GEN-LAST:event_lb_EstMouseClicked

    private void lb_ActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ActMouseClicked
        this.setVisible(false);
        new ActualBudget().setVisible(true);
    }//GEN-LAST:event_lb_ActMouseClicked

    private void lb_SttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SttMouseClicked
        this.setVisible(false);
        new Statistics().setVisible(true);
    }//GEN-LAST:event_lb_SttMouseClicked

    private void lb_AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AccMouseClicked
        new Account().setVisible(true);
    }//GEN-LAST:event_lb_AccMouseClicked

    private void lb_SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SignOutMouseClicked
        new ShowMessageDialog(this, true, "Loging Out ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            this.setVisible(false);
            new Login().setVisible(true);
            Login.status =false;
            Login.admin = false;
            Login.config = true;
        }
    }//GEN-LAST:event_lb_SignOutMouseClicked

    private void txt_CampNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CampNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CampNameActionPerformed

    private void txt_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_perActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Home;
    private javax.swing.ButtonGroup btnGrpCamp;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox chk_finish;
    private javax.swing.JComboBox cmb_Ad;
    private javax.swing.JComboBox cmb_Pro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lb_Acc;
    private javax.swing.JLabel lb_Act;
    private javax.swing.JLabel lb_Admin;
    private javax.swing.JLabel lb_Camp;
    private javax.swing.JLabel lb_Est;
    private javax.swing.JLabel lb_Home;
    private javax.swing.JLabel lb_Pro;
    private javax.swing.JLabel lb_SignOut;
    private javax.swing.JLabel lb_Stt;
    private javax.swing.JRadioButton rd_ID;
    private javax.swing.JRadioButton rd_Name;
    private javax.swing.JTable tb_Camp;
    private javax.swing.JTextField txt_AdID;
    private javax.swing.JTextField txt_CampId;
    private javax.swing.JTextField txt_CampName;
    private javax.swing.JTextArea txt_Des;
    private javax.swing.JTextField txt_End;
    private javax.swing.JTextField txt_ProID;
    private javax.swing.JTextField txt_Start;
    private javax.swing.JTextField txt_per;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
