/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Kernel.AdminPC;
import Kernel.LoginPC;
import Kernel.Validation;
import java.awt.Color;
import java.util.Vector;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asus
 */
public class ChangeInfo extends javax.swing.JFrame {
Vector log_vt = AdminPC.readEmployee();
private String accID;
    /**
     * Creates new form ChangeInfo
     */
    public ChangeInfo() {
        initComponents();
        this.setTitle("CIS-Change Info");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setSize(380, 295);
        this.setResizable(false);
        getData();
    }
private void getData( )
    {
            
            for(int i=0; i< log_vt.size(); i++)
            {
                Vector temp=(Vector) log_vt.elementAt(i);
              accID=Login.EmpID;
              if(accID.equals(temp.elementAt(0).toString()))
                {
                   
                    
                    
                    
                 
                    txt_Age.setText(temp.elementAt(3).toString());
                    
                    txt_Name.setText(temp.elementAt(2).toString());
                    txt_Phone.setText(temp.elementAt(5).toString());
                    
                    txt_Mail.setText(temp.elementAt(4).toString());
                
                    break;
                
            }
        }
    }
 
     private void refresh()
    {
        Vector log_vt = AdminPC.readEmployee();
        
    }
 private Entity.Employee getAdmin()
    {
        Entity.Employee emp = new Entity.Employee();
       
        emp.setEmployeeName(txt_Name.getText().trim());
        emp.setEmail(txt_Mail.getText().trim());
        emp.setPhone(txt_Phone.getText().trim());
        emp.setAge(Integer.parseInt(txt_Age.getText()));
        emp.setEmloyeeID(accID);
        return emp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Mail = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        txt_Age = new javax.swing.JTextField();
        btn_Change = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Emp Mail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 65, -1, -1));

        jLabel3.setText("Emp Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 103, -1, -1));

        jLabel4.setText("Emp Phone:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 141, -1, -1));

        jLabel5.setText("Emp Age:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 179, -1, -1));
        getContentPane().add(txt_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 62, 151, -1));
        getContentPane().add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 100, 151, -1));
        getContentPane().add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 138, 151, -1));
        getContentPane().add(txt_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 176, 151, -1));

        btn_Change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSave.png"))); // NOI18N
        btn_Change.setText("Save");
        btn_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 226, 87, -1));

        btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnExit.png"))); // NOI18N
        btn_Cancel.setText("Close");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 226, 95, -1));

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("(*)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("(*)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("(*)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("(*)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgCInfo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
       this.setVisible(false);
       new Account().setVisible(true);
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeActionPerformed
        if(evt.getActionCommand().equals("Save")){
            if(!Validation.validateComponents(new JTextComponent[]{txt_Name,txt_Phone,txt_Mail,txt_Age}))
            {
                return;
            }
            if(((txt_Name.getText().trim()).length()>50))
        {
            Validation.showMess("Name is restricted to 50 characters");
            txt_Name.requestFocus();
            txt_Name.setBackground(new Color(255,153,153));
            return;
        }
             if(!Validation.isInt(txt_Phone.getText().trim())){
                Validation.showMess("Only numbers are allowed");
                txt_Phone.requestFocus();
                txt_Phone.setBackground(new Color(255,153,153));
                return;
            }else if(((txt_Phone.getText().trim()).length()<8)||((txt_Phone.getText().trim()).length()>15)){
                Validation.showMess("Phone numbers must be between 8 and 15 digits");
                txt_Phone.requestFocus();
                txt_Phone.setBackground(new Color(255,153,153));
                return;
            }
            else if(Long.parseLong(txt_Phone.getText().toString().trim())==0){
                Validation.showMess("Invalid Phone numbers");
                txt_Phone.requestFocus();
                txt_Phone.setBackground(new Color(255,153,153));
                return;
            }
            if(!Validation.isInt(txt_Age.getText().trim())){
                Validation.showMess("Only numbers are allowed");
                txt_Age.requestFocus();
                txt_Age.setBackground(new Color(255,153,153));
                return;
            }
            else if(((Integer.parseInt(txt_Age.getText().trim()))<18)||((Integer.parseInt(txt_Age.getText().trim()))>60)){
                Validation.showMess("Age must be in between of 18 and 60");
                txt_Age.requestFocus();
                txt_Age.setBackground(new Color(255,153,153));
                return;
            }if(((txt_Mail.getText().trim()).length()>50))
        {
            Validation.showMess("Email is restricted to 50 characters");
            txt_Mail.requestFocus();
            txt_Mail.setBackground(new Color(255,153,153));
            return;
        }
           else if(!Validation.isValidEmail(txt_Mail.getText().trim()))
            {
                Validation.showMess("Invalid Email");
                txt_Mail.requestFocus();
                txt_Mail.setBackground(new Color(255,153,153));
                return;
            }
            
            String mess=AdminPC.changeEmployee(getAdmin());
            new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
            refresh();
            this.setVisible(false);
            new Account().setVisible(true);
        }
          
           
            
        
                        
    }//GEN-LAST:event_btn_ChangeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_Mail;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Phone;
    // End of variables declaration//GEN-END:variables
}
