/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Kernel.ActualPC;
import Kernel.EstimatedPC;
import Kernel.Validation;
import java.awt.Color;
import java.sql.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asus
 */
public class EstimateBudget extends javax.swing.JFrame {
    int row=0;
    boolean clickable =true;
    Vector CampaignDetails = ActualPC.getCampaignTable();
    /**
     * Creates new form EstimateBudget
     */
    public EstimateBudget() {
        initComponents();
        if(!Login.admin){
            lb_Admin.setEnabled(false);
            lb_Camp.setEnabled(false);
            lb_Pro.setEnabled(false);
        }
        this.setTitle("CIS-Estimate Budget Master");
        this.setSize(800, 636);
        this.setResizable(false);
        refresh();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void reset(){       
        setBlank();
    }
    
     private boolean validateData()
    {
         if(Validation.isEmpty(txt_estBud.getText().trim())){
                Validation.showMess("Empty value is not allowed");
                txt_estBud.requestFocus();
                txt_estBud.setBackground(new Color(255,153,153));
                return false;
            }
         else if(!Validation.isFloat(txt_estBud.getText().trim())){
                Validation.showMess("Only Float value is accepted");
                txt_estBud.requestFocus();
                txt_estBud.setBackground(new Color(255,153,153));
                return false;
            }
         else if((Float.parseFloat(txt_estBud.getText().trim())<0)){
                Validation.showMess("Only Positive value is accepted");
                txt_estBud.requestFocus();
                txt_estBud.setBackground(new Color(255,153,153));
                return false;
        }
        else if((Float.parseFloat(txt_estBud.getText().trim())>100000)||(Float.parseFloat(txt_estBud.getText().trim())==0)){
            
            Validation.showMess("Value must be in between of 0 and 100000");
            txt_estBud.setBackground(new Color(255,153,153));
            txt_estBud.requestFocus();
            return false;
        }
        if(Validation.isEmpty(txt_estSale.getText().trim())){
                Validation.showMess("Empty value is not allowed");
                txt_estSale.requestFocus();
                txt_estSale.setBackground(new Color(255,153,153));
                return false;
            }
       else if(!Validation.isFloat(txt_estSale.getText().trim())){
                Validation.showMess("Only Float value is accepted");
                txt_estSale.requestFocus();
                txt_estSale.setBackground(new Color(255,153,153));
                return false;
            }
       else if((Float.parseFloat(txt_estSale.getText().trim())<0)){
                Validation.showMess("Only Positive value is accepted");
                txt_estSale.requestFocus();
                txt_estSale.setBackground(new Color(255,153,153));
                return false;
        }
       else if((Float.parseFloat(txt_estSale.getText().trim())>100000)||(Float.parseFloat(txt_estSale.getText().trim())==0)){
            
            Validation.showMess("Value must be in between of 0 and 100000");
            txt_estSale.setBackground(new Color(255,153,153));
            txt_estSale.requestFocus();
            return false;
        }
        if(Validation.isEmpty(txt_estVar.getText().trim())){
                Validation.showMess("Empty value is not allowed");
                txt_estVar.requestFocus();
                txt_estVar.setBackground(new Color(255,153,153));
                return false;
            }                       
       else if(!Validation.isFloat(txt_estVar.getText().trim())){
                Validation.showMess("Only Float value is accepted");
                txt_estVar.requestFocus();
                txt_estVar.setBackground(new Color(255,153,153));
                return false;
            }
       else if((Float.parseFloat(txt_estVar.getText().trim())<0)){
                Validation.showMess("Only Positive value is accepted");
                txt_estVar.requestFocus();
                txt_estVar.setBackground(new Color(255,153,153));
                return false;
        }
       else if((Float.parseFloat(txt_estVar.getText().trim())>100)||(Float.parseFloat(txt_estVar.getText().trim())==0)){
            
            Validation.showMess("Value must be in between of 0 and 100");
            txt_estVar.setBackground(new Color(255,153,153));
            txt_estVar.requestFocus();
            return false;
        }
        return true;
    }
    
    private void setBlank()
    {
        Validation.setBlankField(new JTextComponent[] {txt_estBud, txt_estSale,txt_estVar});
        txt_estBud.requestFocus();
    }
    
    private void refresh()
    {
        CampaignDetails = ActualPC.getCampaignTable();
        txt_campName.setText(null);
        txt_campDes.setText(null);
        lb_campId.setText(null);
        lb_ProName.setText(null);
        lb_adType.setText(null);
        lb_Start.setText(null);
        lb_End.setText(null);
        lb_per.setText(null);
        txt_campName.setEnabled(false);
        txt_campDes.setEnabled(false);
        txt_estBud.setEnabled(false);
        txt_estSale.setEnabled(false);
        txt_estVar.setEnabled(false);
        btn_rs.setEnabled(false);
        btn_save.setText("Update Estimated Data");
        btn_save.setEnabled(true);
        row = 0;
        clickable = true;
        setBlank();
        fillTable();
    }
    
    private void fillTable()
    {
        Vector title = new Vector();
        title.add("Campaign ID");
        title.add("Campaign Name");
        title.add("Estimated Status");


        Vector campaigns = EstimatedPC.readCampaign();
        if(campaigns.size()>0)
        {
            tb_camp.setModel(new DefaultTableModel(campaigns, title));
            tb_camp.getColumnModel().getColumn(0).setPreferredWidth(70);
            tb_camp.getColumnModel().getColumn(1).setPreferredWidth(90);
            tb_camp.getColumnModel().getColumn(2).setPreferredWidth(90);
            tb_camp.setDragEnabled(false);
        }

    }
    
      private void readCampaignDetail(String CampaignID)
    {
        if(CampaignDetails.size()>0)
        {
            for(int i=0; i<CampaignDetails.size(); i++)
            {
                Vector temp=(Vector)CampaignDetails.elementAt(i);
                if(CampaignID.equals(temp.elementAt(0).toString()))
                {
                    lb_campId.setText(temp.elementAt(0).toString());
                    txt_campName.setText(temp.elementAt(1).toString());
                    lb_ProName.setText(temp.elementAt(3).toString());
                   
                    lb_Start.setText(Validation.convertDateToString((Date)temp.elementAt(4)));
                    lb_End.setText(Validation.convertDateToString((Date)temp.elementAt(5)));
                    lb_per.setText(temp.elementAt(6).toString()+" day(s)");
                    
                    lb_adType.setText(temp.elementAt(8).toString());
                    
                    txt_estBud.setText(temp.elementAt(9).toString());
                    txt_estSale.setText(temp.elementAt(11).toString());
                    txt_estVar.setText(temp.elementAt(13).toString());
                    txt_campDes.setText(temp.elementAt(16).toString());
                    
                    break;
                }
            }
        }
    }
      
      private Entity.Campaign getCampaign()
    {
        Entity.Campaign camp = new Entity.Campaign();
        camp.setCampaignID(Integer.parseInt(lb_campId.getText().trim()));
        camp.setEstimatedBudget(Float.parseFloat(txt_estBud.getText().trim()));
        camp.setEstimatedSales(Float.parseFloat(txt_estSale.getText().trim()));
        camp.setEstimatedVariance(Float.parseFloat(txt_estVar.getText().trim()));
        camp.setDescription(txt_campDes.getText().trim());
        return camp;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_camp = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_campName = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lb_campId = new javax.swing.JLabel();
        lb_ProName = new javax.swing.JLabel();
        lb_adType = new javax.swing.JLabel();
        lb_Start = new javax.swing.JLabel();
        lb_End = new javax.swing.JLabel();
        lb_per = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_campDes = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_estBud = new javax.swing.JTextField();
        txt_estSale = new javax.swing.JTextField();
        txt_estVar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_rs = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb_SignOut = new javax.swing.JLabel();
        lb_Acc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_Stt = new javax.swing.JLabel();
        lb_Act = new javax.swing.JLabel();
        lb_Est = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_Camp = new javax.swing.JLabel();
        lb_Pro = new javax.swing.JLabel();
        lb_Admin = new javax.swing.JLabel();
        lb_Home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Menu_Home = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Menu_Exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estimate Budget");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campaign List"));

        tb_camp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campaign ID", "Campaign Name", "Estimated Status"
            }
        ));
        tb_camp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_campMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_camp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel11.setText("Campaign Name:");

        txt_campName.setColumns(20);
        txt_campName.setRows(5);
        jScrollPane2.setViewportView(txt_campName);

        jLabel12.setText("Campaign ID:");

        jLabel13.setText("Product Name:");

        jLabel14.setText("Start Date:");

        jLabel15.setText("Finish Date:");

        jLabel16.setText("Period:");

        jLabel22.setText("Advertisement Type :");

        lb_campId.setText("jLabel1");

        lb_ProName.setText("jLabel2");

        lb_adType.setText("jLabel3");

        lb_Start.setText("jLabel4");

        lb_End.setText("jLabel5");

        lb_per.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel22)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_campId)
                            .addComponent(lb_ProName)
                            .addComponent(lb_adType)
                            .addComponent(lb_Start)
                            .addComponent(lb_End)
                            .addComponent(lb_per)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lb_campId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lb_ProName))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lb_adType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lb_Start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lb_End))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lb_per))
                .addGap(46, 46, 46))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 270));

        jLabel17.setText("Description(details about gifts, discounts, etc...)");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        txt_campDes.setColumns(20);
        txt_campDes.setRows(5);
        jScrollPane3.setViewportView(txt_campDes);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 249, 110));

        jLabel18.setText("Estimated Budget:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel19.setText("Estimated Sale:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jLabel20.setText("Estimated Variance:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));
        getContentPane().add(txt_estBud, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 120, -1));
        getContentPane().add(txt_estSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 120, -1));
        getContentPane().add(txt_estVar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 120, -1));

        jLabel21.setText("(%)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnUpdate.png"))); // NOI18N
        btn_save.setText("Update Estimated Data");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 185, -1));

        btn_rs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnReset.png"))); // NOI18N
        btn_rs.setText("Reset");
        btn_rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 89, -1));

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRefresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_SignOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_SignOut.setForeground(new java.awt.Color(51, 153, 255));
        lb_SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLogout.png"))); // NOI18N
        lb_SignOut.setText("Sign Out");
        lb_SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SignOutMouseClicked(evt);
            }
        });
        jPanel1.add(lb_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 110, -1));

        lb_Acc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Acc.setForeground(new java.awt.Color(51, 153, 255));
        lb_Acc.setText("My Account");
        lb_Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AccMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 146, 10));

        lb_Stt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Stt.setForeground(new java.awt.Color(51, 153, 255));
        lb_Stt.setText("Statistics");
        lb_Stt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SttMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, -1));

        lb_Act.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Act.setForeground(new java.awt.Color(51, 153, 255));
        lb_Act.setText("Actual Budget");
        lb_Act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ActMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 106, -1));

        lb_Est.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Est.setForeground(new java.awt.Color(51, 153, 255));
        lb_Est.setText("Estimate Budget");
        lb_Est.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_EstMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 146, 10));

        lb_Camp.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Camp.setForeground(new java.awt.Color(51, 153, 255));
        lb_Camp.setText("Campaign Master");
        lb_Camp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_CampMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Camp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));

        lb_Pro.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Pro.setForeground(new java.awt.Color(51, 153, 255));
        lb_Pro.setText("Product Master");
        lb_Pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ProMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 114, -1));

        lb_Admin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Admin.setForeground(new java.awt.Color(51, 153, 255));
        lb_Admin.setText("Administration");
        lb_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AdminMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 114, -1));

        lb_Home.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Home.setForeground(new java.awt.Color(51, 153, 255));
        lb_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconHome.png"))); // NOI18N
        lb_Home.setText("Home");
        lb_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HomeMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgMenu.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel31.setText("$");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel32.setText("$");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("(*)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("(*)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("(*)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgTemplete.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 580));

        jMenu3.setText("Menu");

        Menu_Home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        Menu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_HomeActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Home);
        jMenu3.add(jSeparator3);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Exit.setText("Exit");
        Menu_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ExitMouseClicked(evt);
            }
        });
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Exit);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem1.setText("User Guide is temporarily not available");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_campMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_campMouseClicked
        if(clickable == true){
        if (tb_camp.getSelectedRow() == -1) {
            new ShowMessageDialog(null, true, "Please choose a row",  ShowMessageDialog.MESSAGE);
            return;
        }
        row = tb_camp.getSelectedRow();
        readCampaignDetail((String)tb_camp.getValueAt(row, 0));
        }
    }//GEN-LAST:event_tb_campMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(evt.getActionCommand().equals("Update Estimated Data")){
            if (tb_camp.getSelectedRow() == -1) {
            new ShowMessageDialog(null, true, "Please choose a row",  ShowMessageDialog.MESSAGE);
            return;
            }else{
            clickable = false;    
            btn_save.setText("Save Estimated Data");
            txt_estBud.setEnabled(true);
            txt_estSale.setEnabled(true);
            txt_estVar.setEnabled(true);
            btn_rs.setEnabled(true);
            }
        }else if(evt.getActionCommand().equals("Save Estimated Data")){
                
            if( ! validateData()){
            return;
            }
            String mess = EstimatedPC.updateCampaign(this.getCampaign());
            new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
            btn_save.setText("Update Estimated Data");
            clickable = true;  
            refresh();
            fillTable();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_rsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rsActionPerformed
        setBlank();
    }//GEN-LAST:event_btn_rsActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked

    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HomeActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Menu_HomeActionPerformed

    private void Menu_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ExitMouseClicked

    }//GEN-LAST:event_Menu_ExitMouseClicked

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        new ShowMessageDialog(this, true, "Do you want to exit the program ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void lb_SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SignOutMouseClicked
        new ShowMessageDialog(this, true, "Loging Out ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            this.setVisible(false);
            new Login().setVisible(true);
            Login.status =false;
            Login.admin = false;
            Login.config = true;
        }
    }//GEN-LAST:event_lb_SignOutMouseClicked

    private void lb_AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AccMouseClicked
        new Account().setVisible(true);
    }//GEN-LAST:event_lb_AccMouseClicked

    private void lb_SttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SttMouseClicked
        this.setVisible(false);
        new Statistics().setVisible(true);
    }//GEN-LAST:event_lb_SttMouseClicked

    private void lb_ActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ActMouseClicked
        this.setVisible(false);
        new ActualBudget().setVisible(true);
    }//GEN-LAST:event_lb_ActMouseClicked

    private void lb_EstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_EstMouseClicked
        this.setVisible(false);
        new EstimateBudget().setVisible(true);
    }//GEN-LAST:event_lb_EstMouseClicked

    private void lb_CampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_CampMouseClicked
        if(lb_Camp.isEnabled())
        {
            this.setVisible(false);
            new CampaignMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_CampMouseClicked

    private void lb_ProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ProMouseClicked
        if(lb_Pro.isEnabled()){
            this.setVisible(false);
            new ProductMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_ProMouseClicked

    private void lb_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AdminMouseClicked
        if(lb_Admin.isEnabled()){
            this.setVisible(false);
            new Administration().setVisible(true);
        }
    }//GEN-LAST:event_lb_AdminMouseClicked

    private void lb_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HomeMouseClicked
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_lb_HomeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Home;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_rs;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lb_Acc;
    private javax.swing.JLabel lb_Act;
    private javax.swing.JLabel lb_Admin;
    private javax.swing.JLabel lb_Camp;
    private javax.swing.JLabel lb_End;
    private javax.swing.JLabel lb_Est;
    private javax.swing.JLabel lb_Home;
    private javax.swing.JLabel lb_Pro;
    private javax.swing.JLabel lb_ProName;
    private javax.swing.JLabel lb_SignOut;
    private javax.swing.JLabel lb_Start;
    private javax.swing.JLabel lb_Stt;
    private javax.swing.JLabel lb_adType;
    private javax.swing.JLabel lb_campId;
    private javax.swing.JLabel lb_per;
    private javax.swing.JTable tb_camp;
    private javax.swing.JTextArea txt_campDes;
    private javax.swing.JTextArea txt_campName;
    private javax.swing.JTextField txt_estBud;
    private javax.swing.JTextField txt_estSale;
    private javax.swing.JTextField txt_estVar;
    // End of variables declaration//GEN-END:variables
}
