/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Kernel.AdminPC;
import Kernel.Validation;
import java.awt.Color;
import java.util.Vector;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asus
 */
public class PasswordChange extends javax.swing.JFrame {
Vector EmployeeDetails = AdminPC.readEmployee();
private String accID;

    /**
     * Creates new form PasswordChange
     */
    public PasswordChange() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        accID=Login.EmpID;
        this.setTitle("CIS-Change Password");
        this.setSize(380, 295);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private void refresh()
    {
        Vector log_vt = AdminPC.readEmployee();
        
    }
    private Entity.Employee getAdmin()
    {
        Entity.Employee emp = new Entity.Employee();
       
        emp.setPassword(txt_Pass.getText().trim());
        emp.setEmloyeeID(accID);
        return emp;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_OK = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Pass = new javax.swing.JPasswordField();
        txt_RePass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSave.png"))); // NOI18N
        Btn_OK.setText("Save");
        Btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OKActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 197, -1, -1));

        btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnExit.png"))); // NOI18N
        btn_Cancel.setText("Close");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 197, 95, -1));

        jLabel3.setText("New Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, -1, -1));

        jLabel4.setText("Password Confirm:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 140, -1, -1));
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 99, 180, -1));
        getContentPane().add(txt_RePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 137, 180, -1));

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("(*)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("(*)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgCPass.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
       this.setVisible(false);
       new Account().setVisible(true);
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void Btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OKActionPerformed
       if(!Validation.validateComponents(new JTextComponent[]{txt_Pass,txt_RePass,}))
        {
            return;
        }       
       else if(new String(txt_Pass.getPassword().toString().trim()).length()>40)
        {
            Validation.showMess("Employee Password is restricted to 40 characters");
            txt_Pass.requestFocus();
            txt_Pass.setBackground(new Color(255,153,153));
            return;
        }else if(!(new String(txt_RePass.getPassword())).equals(new String(txt_Pass.getPassword()))){
            
            Validation.showMess("Password Confirmation is not matched");
            txt_RePass.requestFocus();
            return;
       } 
     
        String mess=AdminPC.changePass(getAdmin());
        new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
         refresh();
        this.setVisible(false);
        new Account().setVisible(true);   
    }//GEN-LAST:event_Btn_OKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_OK;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JPasswordField txt_RePass;
    // End of variables declaration//GEN-END:variables
}
