/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Product;
import Kernel.ProductPC;
import Kernel.Validation;
import Kernel.dataPC;
import java.awt.Color;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Asus
 */
public class ProductMaster extends javax.swing.JFrame {
    int row =0;
    boolean clickable =true;
    boolean update = false;
    /**
     * Creates new form ProductMaster
     */
    public ProductMaster() {
        initComponents();
        this.setTitle("CIS-Product Master");
        this.setSize(800, 636);
        this.setResizable(false);
        if(!Login.admin){
            lb_Admin.setEnabled(false);
            lb_Camp.setEnabled(false);
            lb_Pro.setEnabled(false);
        }
        dataPC.readToComboBox("[CIS].[dbo].[Category]",cmb_CateName,"CateName");
        loadDataToTable();
        reset();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpPro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb_Home = new javax.swing.JLabel();
        lb_Admin = new javax.swing.JLabel();
        lb_Pro = new javax.swing.JLabel();
        lb_Camp = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_Est = new javax.swing.JLabel();
        lb_Act = new javax.swing.JLabel();
        lb_Stt = new javax.swing.JLabel();
        lb_Acc = new javax.swing.JLabel();
        lb_SignOut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Find = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        rd_Id = new javax.swing.JRadioButton();
        rd_Name = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Product = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ProID = new javax.swing.JTextField();
        txt_ProName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ProDes = new javax.swing.JTextArea();
        btn_Ins = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_CateName = new javax.swing.JComboBox();
        txt_CateID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Menu_Home = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Menu_Exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Home.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Home.setForeground(new java.awt.Color(51, 153, 255));
        lb_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconHome.png"))); // NOI18N
        lb_Home.setText("Home");
        lb_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HomeMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        lb_Admin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Admin.setForeground(new java.awt.Color(51, 153, 255));
        lb_Admin.setText("Administration");
        lb_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AdminMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 114, -1));

        lb_Pro.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Pro.setForeground(new java.awt.Color(51, 153, 255));
        lb_Pro.setText("Product Master");
        lb_Pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ProMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 114, -1));

        lb_Camp.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Camp.setForeground(new java.awt.Color(51, 153, 255));
        lb_Camp.setText("Campaign Master");
        lb_Camp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_CampMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Camp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 146, 10));

        lb_Est.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Est.setForeground(new java.awt.Color(51, 153, 255));
        lb_Est.setText("Estimate Budget");
        lb_Est.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_EstMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, -1));

        lb_Act.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Act.setForeground(new java.awt.Color(51, 153, 255));
        lb_Act.setText("Actual Budget");
        lb_Act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ActMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 106, -1));

        lb_Stt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Stt.setForeground(new java.awt.Color(51, 153, 255));
        lb_Stt.setText("Statistics");
        lb_Stt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SttMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, -1));

        lb_Acc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_Acc.setForeground(new java.awt.Color(51, 153, 255));
        lb_Acc.setText("My Account");
        lb_Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_AccMouseClicked(evt);
            }
        });
        jPanel1.add(lb_Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));

        lb_SignOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lb_SignOut.setForeground(new java.awt.Color(51, 153, 255));
        lb_SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLogout.png"))); // NOI18N
        lb_SignOut.setText("Sign Out");
        lb_SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_SignOutMouseClicked(evt);
            }
        });
        jPanel1.add(lb_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 146, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgMenu.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Product Master");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        btn_Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSearch.png"))); // NOI18N
        btn_Find.setText("Find");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 140, -1));

        rd_Id.setBackground(new java.awt.Color(255, 255, 255));
        btnGrpPro.add(rd_Id);
        rd_Id.setSelected(true);
        rd_Id.setText("Product ID");
        getContentPane().add(rd_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, -1));

        rd_Name.setBackground(new java.awt.Color(255, 255, 255));
        btnGrpPro.add(rd_Name);
        rd_Name.setText("Product Name");
        getContentPane().add(rd_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Product List"));

        tb_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Description"
            }
        ));
        tb_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Product);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 630, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Product ID:");

        jLabel12.setText("Product Name:");

        jLabel13.setText("Description:");

        txt_ProDes.setColumns(20);
        txt_ProDes.setRows(5);
        jScrollPane2.setViewportView(txt_ProDes);

        btn_Ins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnInsert.png"))); // NOI18N
        btn_Ins.setText("Create");
        btn_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsActionPerformed(evt);
            }
        });

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnUpdate.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDelete.png"))); // NOI18N
        btn_Del.setText("Delete");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRefresh.png"))); // NOI18N
        btn_Refresh.setText("Refresh");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });

        jLabel1.setText("Category Name:");

        cmb_CateName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select>" }));
        cmb_CateName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CateNameItemStateChanged(evt);
            }
        });
        cmb_CateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CateNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Category ID:");

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("(*)");

        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("(*)");

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("(*)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Ins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Refresh))
                    .addComponent(txt_ProID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ProName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmb_CateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_CateID))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ProID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_ProName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_CateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Ins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13)))
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 610, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgTemplete.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 580));

        jMenu3.setText("Menu");

        Menu_Home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Home.setText("Home");
        Menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_HomeMouseClicked(evt);
            }
        });
        Menu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_HomeActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Home);
        jMenu3.add(jSeparator3);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Exit.setText("Exit");
        Menu_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ExitMouseClicked(evt);
            }
        });
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Exit);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem1.setText("User Guide is temporarily not available");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Product getProduct()
    {
        Product pro=new Product();
        if(update == true){
        pro.setProductID(Integer.parseInt(txt_ProID.getText().trim()));}
        pro.setProductName(txt_ProName.getText().trim());
        pro.setCateId(txt_CateID.getText());
        pro.setDescription(txt_ProDes.getText().trim());
        
        
        return pro;
    }
    
    private void reset()
    {
        loadDataToTable();
        Validation.setBlankField(new JTextComponent[]{txt_ProID,txt_ProName,txt_CateID,txt_ProDes});
        txt_ProID.setEnabled(false);
        txt_ProName.setEnabled(false);
        txt_ProDes.setEnabled(false);
        txt_CateID.setEnabled(false);
        cmb_CateName.setSelectedIndex(0);
        cmb_CateName.setEnabled(false);
        
        btn_Find.setEnabled(true);
        btn_Del.setEnabled(true);
        btn_Ins.setEnabled(true);
        btn_Ins.setText("Create");
        btn_Update.setEnabled(true);
        btn_Update.setText("Update");
        btn_Refresh.setEnabled(true);
        
        txt_ProName.setEditable(true);
        txt_ProDes.setEditable(true);
        txt_CateID.setEditable(true);
        row = 0;
        clickable = true;
        update = false;
                
    }
    
    private void loadDataToTable()
    {
        Vector tit=new Vector();
        tit.add("Product ID");
        tit.add("Category ID");
        tit.add("Product Name");
        tit.add("Category Name");
        tit.add("Description");
        Vector data=ProductPC.readProduct();
        tb_Product.setModel(new DefaultTableModel(data, tit));
    }
    
    
    private void btn_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("Create")){
            reset();
            clickable = false;
            btn_Ins.setText("Save");
            //Deactivate buttons
            btn_Del.setEnabled(false);
            btn_Find.setEnabled(false);
            btn_Refresh.setEnabled(true);
            btn_Update.setEnabled(false);
            
            //Activate Edit for textbox and combobox and checkbox
            cmb_CateName.setEnabled(true);
            txt_CateID.setEnabled(true);
            txt_ProName.setEnabled(true);
            txt_ProDes.setEnabled(true);
            txt_ProName.setEditable(true);

            txt_CateID.setEditable(false);

            }
            
        if(evt.getActionCommand().equals("Save")){      
        if(!Validation.validateComponents(new JTextComponent[]{txt_ProName,txt_CateID,txt_ProDes}))
        {
            return;
        }if(((txt_ProName.getText().trim()).length()>50))
        {
            Validation.showMess("Product Name is restricted to 50 characters");
            txt_ProName.requestFocus();
            txt_ProName.setBackground(new Color(255,153,153));
            return;
        }if(((txt_ProDes.getText().trim()).length()>50))
        {
            Validation.showMess("Product Description is restricted to 50 characters");
            txt_ProDes.requestFocus();
            txt_ProDes.setBackground(new Color(255,153,153));
            return;
        }
        String mess=ProductPC.insertProduct(getProduct());
        new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
        btn_Ins.setText("Create");
        clickable = true;
        //Deactivate buttons
        reset();

            
        }
    }//GEN-LAST:event_btn_InsActionPerformed

    private void tb_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ProductMouseClicked
        // TODO add your handling code here:
        if(clickable == true){
            row = tb_Product.getSelectedRow();
        boolean fn=false;
         
        if(row!=-1){
            
            txt_ProID.setText(""+tb_Product.getValueAt(row, 0));
            txt_ProName.setText(""+tb_Product.getValueAt(row, 2));
            cmb_CateName.setSelectedItem(tb_Product.getValueAt(row, 3));
            txt_ProDes.setText(""+tb_Product.getValueAt(row, 4));
            
            }
        }    
    }//GEN-LAST:event_tb_ProductMouseClicked

    private void cmb_CateNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CateNameItemStateChanged
        if(cmb_CateName.getSelectedIndex()==0){
            txt_CateID.setText(null);
        }else{
            String values=(String)cmb_CateName.getSelectedItem();
            txt_CateID.setText(dataPC.getAnotherField("[CIS].[dbo].[Category]","CateName","CateID", values));
        }
    }//GEN-LAST:event_cmb_CateNameItemStateChanged

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void cmb_CateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_CateNameActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        // TODO add your handling code here:
        if(tb_Product.getSelectedRow()==-1)
        {
            new ShowMessageDialog(null, true,"Please chose a row",ShowMessageDialog.MESSAGE);
            return;
        }
        new ShowMessageDialog(null, true,"<html><Center>Do you really want delete this Product ?<br>All campaign associate with this Product will be deleted as well</Center></html>",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
           String mess= ProductPC.deleteProduct(txt_ProID.getText());
           new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
           reset();
        }
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
                if(evt.getActionCommand().equals("Update")){
            if (tb_Product.getSelectedRow() == -1) {
            new ShowMessageDialog(null, true, "Please choose a row",  ShowMessageDialog.MESSAGE);
            return;
            }else{
            clickable = false;
            btn_Update.setText("Save");
            //Deactivate buttons
            btn_Del.setEnabled(false);
            btn_Find.setEnabled(false);
            btn_Refresh.setEnabled(true);
            btn_Ins.setEnabled(false);
            //Activate Edit for textbox and combobox and checkbox
            cmb_CateName.setEnabled(true);
            txt_CateID.setEnabled(true);
            txt_ProName.setEnabled(true);
            txt_ProDes.setEnabled(true);
            
            txt_CateID.setEditable(false);
            
            //activate update protocol
            update = true;
             }
        }
        if(evt.getActionCommand().equals("Save")){
        if(!Validation.validateComponents(new JTextComponent[]{txt_ProName,txt_ProDes}))
        {
            return;
        }if(((txt_ProName.getText().trim()).length()>50))
        {
            Validation.showMess("Product Name is restricted to 50 characters");
            txt_ProName.requestFocus();
            txt_ProName.setBackground(new Color(255,153,153));
            return;
        }if(((txt_ProDes.getText().trim()).length()>50))
        {
            Validation.showMess("Product Description is restricted to 50 characters");
            txt_ProDes.requestFocus();
            txt_ProDes.setBackground(new Color(255,153,153));
            return;
        }    
        String mess=ProductPC.updateProduct(getProduct());
        new ShowMessageDialog(null, true, mess, ShowMessageDialog.MESSAGE);
        reset();
        btn_Update.setText("Update");
        clickable = true;
        update = false;
        //Reactivate buttons
            reset();
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        // TODO add your handling code here:
        int ByID=1;
        int ByName=2;
        Vector vt;
        if(Validation.isEmpty(txt_search.getText()))
        {
            Validation.showMess("Please enter any words to find");
            txt_search.requestFocus();
            txt_search.setBackground(new Color(255,153,153));
            return;
        }
        if(rd_Id.isSelected())
        {
            vt=ProductPC.FindProduct(txt_search.getText(), ByID);
        }
        else
        {
            vt=ProductPC.FindProduct(txt_search.getText(), ByName);
        }
        Vector tit=new Vector();
        tit.add("ProID");
        tit.add("CateID");
        tit.add("ProName");
        tit.add("CateName");
        tit.add("Description");
        tb_Product.setModel(new DefaultTableModel(vt, tit));
        txt_search.setText("");
    }//GEN-LAST:event_btn_FindActionPerformed

    private void Menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_HomeMouseClicked

    }//GEN-LAST:event_Menu_HomeMouseClicked

    private void Menu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HomeActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Menu_HomeActionPerformed

    private void Menu_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ExitMouseClicked

    }//GEN-LAST:event_Menu_ExitMouseClicked

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        new ShowMessageDialog(this, true, "Do you want to exit the program ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void lb_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HomeMouseClicked
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_lb_HomeMouseClicked

    private void lb_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AdminMouseClicked
        if(lb_Admin.isEnabled()){
            this.setVisible(false);
            new Administration().setVisible(true);
        }
    }//GEN-LAST:event_lb_AdminMouseClicked

    private void lb_ProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ProMouseClicked
        if(lb_Pro.isEnabled()){
            this.setVisible(false);
            new ProductMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_ProMouseClicked

    private void lb_CampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_CampMouseClicked
        if(lb_Camp.isEnabled())
        {
            this.setVisible(false);
            new CampaignMaster().setVisible(true);
        }
    }//GEN-LAST:event_lb_CampMouseClicked

    private void lb_EstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_EstMouseClicked
        this.setVisible(false);
        new EstimateBudget().setVisible(true);
    }//GEN-LAST:event_lb_EstMouseClicked

    private void lb_ActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ActMouseClicked
        this.setVisible(false);
        new ActualBudget().setVisible(true);
    }//GEN-LAST:event_lb_ActMouseClicked

    private void lb_SttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SttMouseClicked
        this.setVisible(false);
        new Statistics().setVisible(true);
    }//GEN-LAST:event_lb_SttMouseClicked

    private void lb_AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_AccMouseClicked
        new Account().setVisible(true);
    }//GEN-LAST:event_lb_AccMouseClicked

    private void lb_SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_SignOutMouseClicked
        new ShowMessageDialog(this, true, "Loging Out ?",ShowMessageDialog.CONFIRM);
        if(ShowMessageDialog.STATUS==ShowMessageDialog.OK)
        {
            this.setVisible(false);
            new Login().setVisible(true);
            Login.status =false;
            Login.admin = false;
            Login.config = true;
        }
    }//GEN-LAST:event_lb_SignOutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Home;
    private javax.swing.ButtonGroup btnGrpPro;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_Ins;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox cmb_CateName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lb_Acc;
    private javax.swing.JLabel lb_Act;
    private javax.swing.JLabel lb_Admin;
    private javax.swing.JLabel lb_Camp;
    private javax.swing.JLabel lb_Est;
    private javax.swing.JLabel lb_Home;
    private javax.swing.JLabel lb_Pro;
    private javax.swing.JLabel lb_SignOut;
    private javax.swing.JLabel lb_Stt;
    private javax.swing.JRadioButton rd_Id;
    private javax.swing.JRadioButton rd_Name;
    private javax.swing.JTable tb_Product;
    private javax.swing.JTextField txt_CateID;
    private javax.swing.JTextArea txt_ProDes;
    private javax.swing.JTextField txt_ProID;
    private javax.swing.JTextField txt_ProName;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
